// <auto-generated />
using System;
using DatabaseLibrary.Entities.Client;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLibrary.Migrations.DbContextClientMigrations
{
    [DbContext(typeof(DbContextClient))]
    partial class DbContextClientModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.CRDTCharacterClient", b =>
                {
                    b.Property<int>("IdCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("TEXT");

                    b.Property<char>("Character")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClockDateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("IdLeftCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("IdRightCharacter")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opperation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Tombstone")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdCharacter", "IdNote");

                    b.HasIndex("IdNote");

                    b.ToTable("CRDTCharacters");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.NoteClient", b =>
                {
                    b.Property<Guid>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirtyFlagChangesMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdNote");

                    b.ToTable("Note");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.Note_UserClient", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser", "IdNote");

                    b.HasIndex("IdNote");

                    b.ToTable("Note_User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.SyncQueueClient", b =>
                {
                    b.Property<int>("IdSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentChanges")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSync");

                    b.HasIndex("IdNote");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.UserClient", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.CRDTCharacterClient", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Client.NoteClient", "NoteClient")
                        .WithMany()
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NoteClient");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.Note_UserClient", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Client.NoteClient", "Note")
                        .WithMany("NoteUser")
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.Client.UserClient", "User")
                        .WithMany("NotesUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.SyncQueueClient", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Client.NoteClient", "Note")
                        .WithMany()
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.NoteClient", b =>
                {
                    b.Navigation("NoteUser");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Client.UserClient", b =>
                {
                    b.Navigation("NotesUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
