// <auto-generated />
using System;
using DatabaseLibrary.Entities.Server;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLibrary.Migrations
{
    [DbContext(typeof(DbContextServer))]
    partial class DbContextServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.Device", b =>
                {
                    b.Property<Guid>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("IdDevice");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.NoteServer", b =>
                {
                    b.Property<Guid>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<bool>("DirtyFlagChangesMade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("datetime('now')");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("version")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdNote");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.Note_UserServer", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser", "IdNote");

                    b.HasIndex("IdNote");

                    b.ToTable("Note_User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.SyncQueueServer", b =>
                {
                    b.Property<int>("IdSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentChanges")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdDevice")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdNote")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSync");

                    b.HasIndex("IdDevice");

                    b.HasIndex("IdNote");

                    b.HasIndex("IdUser");

                    b.ToTable("SyncQueue");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.UserServer", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.User_Device", b =>
                {
                    b.Property<Guid>("IdUser")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdDevice")
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser", "IdDevice");

                    b.HasIndex("IdDevice");

                    b.ToTable("User_Devices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.Note_UserServer", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Server.NoteServer", "Note")
                        .WithMany("NoteUser")
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.Server.UserServer", "User")
                        .WithMany("NotesUser")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.SyncQueueServer", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Server.Device", "Device")
                        .WithMany()
                        .HasForeignKey("IdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.Server.NoteServer", "Note")
                        .WithMany()
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.Server.UserServer", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.User_Device", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Server.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("IdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.Server.UserServer", "User")
                        .WithMany("DevicesUser")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.Device", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.NoteServer", b =>
                {
                    b.Navigation("NoteUser");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Server.UserServer", b =>
                {
                    b.Navigation("DevicesUser");

                    b.Navigation("NotesUser");
                });
#pragma warning restore 612, 618
        }
    }
}
