// <auto-generated />
using DatabaseLibrary.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLibrary.Migrations.Server
{
    [DbContext(typeof(DbContextServer))]
    partial class DbContextServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DatabaseLibrary.Entities.Device", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDevice");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Note", b =>
                {
                    b.Property<int>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CreationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DirtyFlagChangesMade")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordNote")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNote");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Note_User", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdNote")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUser", "IdNote");

                    b.HasIndex("IdNote");

                    b.ToTable("Note_Users");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.UserClient", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("UserClient");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserClient");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User_Device", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdDevice")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUser", "IdDevice");

                    b.HasIndex("IdDevice");

                    b.ToTable("User_Devices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User", b =>
                {
                    b.HasBaseType("DatabaseLibrary.Entities.UserClient");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Note_User", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Note", "Note")
                        .WithMany("NoteUser")
                        .HasForeignKey("IdNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.UserClient", "User")
                        .WithMany("NotesUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Note");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User_Device", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.Device", "Device")
                        .WithMany("UserDevices")
                        .HasForeignKey("IdDevice")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.User", "User")
                        .WithMany("UserDevices")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Device", b =>
                {
                    b.Navigation("UserDevices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Note", b =>
                {
                    b.Navigation("NoteUser");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.UserClient", b =>
                {
                    b.Navigation("NotesUsers");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User", b =>
                {
                    b.Navigation("UserDevices");
                });
#pragma warning restore 612, 618
        }
    }
}
