// <auto-generated />
using DatabaseLibrary.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseLibrary.Migrations.Server
{
    [DbContext(typeof(DbContextServer))]
    partial class DbContextServerModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("DatabaseLibrary.Entities.Device", b =>
                {
                    b.Property<int>("IdDevice")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdDevice");

                    b.HasIndex("IdUser");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.ServerNote", b =>
                {
                    b.Property<int>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StartingDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("lastUpdate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdNote");

                    b.ToTable("ServerNotes");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.ServerNoteUser", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<int>("IdServerNote")
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(1);

                    b.HasKey("IdUser", "IdServerNote");

                    b.HasIndex("IdServerNote");

                    b.ToTable("ServerNoteUsers");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.Device", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.User", "User")
                        .WithMany("Devices")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.ServerNoteUser", b =>
                {
                    b.HasOne("DatabaseLibrary.Entities.ServerNote", "ServerNotes")
                        .WithMany("ServerNoteUser")
                        .HasForeignKey("IdServerNote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabaseLibrary.Entities.User", "User")
                        .WithMany("ServerNotesUsers")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServerNotes");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.ServerNote", b =>
                {
                    b.Navigation("ServerNoteUser");
                });

            modelBuilder.Entity("DatabaseLibrary.Entities.User", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("ServerNotesUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
